"""empty message

Revision ID: 67c1bad63309
Revises: 73b435a33e9c
Create Date: 2025-05-18 09:38:43.814298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c1bad63309'
down_revision = '73b435a33e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        pass 

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('isPromotion')
        batch_op.drop_column('status')
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('originalPrice')

    # ### end Alembic commands ###
