"""Add reset password fields to User

Revision ID: 69819a7e566f
Revises: 
Create Date: 2025-05-17 00:28:22.618604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69819a7e566f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_password_expiration', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_user_reset_password_token', ['reset_password_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_reset_password_token', type_='unique')
        batch_op.drop_column('reset_password_expiration')
        batch_op.drop_column('reset_password_token')

    # ### end Alembic commands ###
