"""empty message

Revision ID: 73b435a33e9c
Revises: 69819a7e566f
Create Date: 2025-05-18 09:35:10.273805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b435a33e9c'
down_revision = '69819a7e566f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('originalPrice', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('imageUrl', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('isPromotion', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('isPromotion')
        batch_op.drop_column('status')
        batch_op.drop_column('imageUrl')
        batch_op.drop_column('originalPrice')

    # ### end Alembic commands ###
